name: testthat-only

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  testthat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            devtools
            testthat
          needs: test

      - name: Run testthat tests
        run: Rscript -e 'devtools::test()'
